# Site settings
title: Flow
tagline: A Jekyll Theme
description: Flow is a simple and elegant SPA-inspired portfolio theme for Jekyll.
baseurl: '' # The subpath of your site, e.g. /blog
url: '' # The base hostname & protocol for your site

# Build settings
client:
  intro: Hello, I'm
  name: Jam Min
  profession: Web Developer
  portrait_url:

social:
  - platform:
    handle:

sass:
  style: compressed
  sourcemap: never
  # load_paths:
  #   - _sass/color-presets

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/
  - vendor/
  - .github/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - LICENSE
  - README
