# Site settings
title: Flow | A Jekyll Theme
description: We don't know much about this website, but we're sure it's great! # Short description of the site which will appear in search engines
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://example.com' # The base hostname & protocol for your site

# Build settings
client:
  name: Human
  profession: Definitely not a robot
  portrait_url:

social:
  - platform:
    handle:

collections_dir: ./_collections
collections:
  articles:
    output: true

sass:
  style: compressed
  # load_paths:
  #   - _sass/color-presets

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/
  - vendor/
  - .github/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - LICENSE
  - README
