# Site settings
title: # The title of your site
description: # Short description of your site that will appear in search engines
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://example.com' # The base hostname & protocol for your site

# Build settings
client:
  intro: # Hello, I'm { name }!
  name: # John Doe | Jane D.
  profession: # Doer of things
  portrait_url: https://avatars.githubusercontent.com/u/42326027?v=4 # Leave blank to use local portrait in assets/

social:
  - platform: GitHub
    handle: benjammin4dayz

theme: flow
colors:
  preset: 0 # 1 = Elegant Lavender | 2 = Candy Crush | 3 = Cotton Candy | 4 = Coral Reef
  use_custom: false # Toggle colors defined below this
  primary:
  secondary:
  tertiary:
  accent:
  accent_alt:
  text:

collections_dir: ./_collections
collections:
  articles:
    output: true
